version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - mail

  mail:
    image: namshi/smtp
    ports:
      - "1025:25"
